# Generated by Django 4.2 on 2024-01-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_lesson_project'),
        ('quizes', '0002_alter_quiz_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='project',
            field=models.ForeignKey(default='8fd8d246-8b97-439b-8291-9f85fb156483', on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='projects.project'),
        ),
    ]
