# Generated by Django 4.2 on 2024-02-08 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0003_quiz_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_points',
            field=models.IntegerField(default=10),
        ),
    ]
