# Generated by Django 4.2 on 2024-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_incorrectquestion_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='incorrectquestion',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
