# Generated by Django 4.2 on 2024-02-27 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_lessonsection_image_delete_lessonimage'),
        ('questions', '0005_incorrectquestion_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incorrectquestion',
            name='lesson',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.lesson'),
        ),
    ]
