# Generated by Django 4.2 on 2024-01-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_lesson_image_lessonsection_lessonimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonsection',
            name='term_definition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
