# Generated by Django 4.2 on 2024-03-06 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_lesson_number'),
        ('users', '0003_remove_profile_bio_remove_profile_short_intro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
