# Generated by Django 4.2 on 2024-03-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_current_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_module',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
