# Generated by Django 4.2 on 2024-03-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_current_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_quiz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
