# Generated by Django 4.2 on 2024-03-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_current_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='modules_completed',
            field=models.IntegerField(default=0),
        ),
    ]
